### ISSUE TITLE
ood.pif.gov

### ISSUE THREAD

**Issue by ghost** [fellows-in-innovation/website#4]
Hi Ross

I was searching for Fellows In Innovation today I came across the old domain which is ood.pif.gov and also show the updated site which is fellowsininnovation.pif.gov these two show one below the other on google if you search for FellowsInInnovation.pif on google.I just thought of letting you know and bringing it to your notice.Congrats on your new role at MSFT.
https://ood.pif.gov/

Thanks,
Neil

**Comment by rossdakin** [comment]
Thanks Neil — looks like ood.pif.gov got pointed to the wrong site.

@stroupaloop would you mind killing ood.pif.gov? It was an early domain for the Opportunity Project and is currently pointed at the wrong CF app. Thanks!

**Comment by rossdakin** [comment]
CC @afeld

**Comment by afeld** [comment]
Should the domain just go away, or should it redirect (to something)?

**Comment by rossdakin** [comment]
It can just go away, or redirect to opportunity.census.gov but only if it's trivially easy -- ood.pif.gov was only ever used internally.

**Comment by stroupaloop** [comment]
@jezhumble and I are working on this, removing the route and should be resolved soon. Thanks!
